
service:
  name: nginx-service
  type: NodePort
  app: product
  protocol: TCP
  port: 80


mynginx:
  name: nginx-service
  app: product
  replicas: 3
  image: nginx:latest
  imagePullPolicy: Always
  containerPort: 80
  protocol : TCP
